In [ ]:
{
    "C1":["A",'B','C','D','E'],
    "C2":["A",'B','F','G','H'],
    "C3":["N",'Y','C','Z','X'],
    "C4":["F",'C','S','B','E'],
    "C5":["Q",'B','K','V','G'],
    "C6":["A",'F','R','W','E'],
    "C7":["A",'L','C','J','E']
    
}
CASE : 1
TOTAL NO. OF UNIQUE ITEMS:15

 ITEAMS   FREQUENCY
   'A'       4
   'B'       3
   'C'       3
.
.
.
.
.

CASE :2

("A",'B') :2 
("A",'C') :2
("A",'D') :1
("A",'E') :3  
("A",'F') :2
("A",'G') :1
.
.
.
.
.

In [ ]:
data= {
    "C1":["A",'B','C','D','E'],
    "C2":["A",'B','F','G','H'],
    "C3":["N",'Y','C','Z','X'],
    "C4":["F",'C','S','D','E'],
    "C5":["Q",'B','K','V','G'],
    "C6":["A",'F','R','W','E'],
    "C7":["A",'L','C','J','E']
    
}

step 1: Convert data into transaction(change all rows as a columns)


T_id           Items
T1            A,A,N,F,Q,A,A
T2            B,B,Y,C,B,F,L
T3            C,F,C,S,K,R,C
T4            D,G,Z,D,V,W,J
T5            E,H,X,E,G,E,E

STEP 2: Count each item's appearance across all transaction 

Items     Frequency    SUPPORT
 A            4        (4/5)*100 :  80%  
 B            3        (3/5)*100 :  60%
 C            4        (4/5)*100 :  80%  
 D            2        (2/5)*100 :  40%  
 E            4        (4/5)*100 :  80%  
 F            3        (3/5)*100 :  60%
 G            2        (2/5)*100 :  40%  
 H            1        (1/5)*100 :  20%  
 J            1
 K            1
 L            1
 N            1
 Q            1
 R            1
 S            1
 V            1
 W            1
 X            1
 Z            1

APPLY : FREQUENT ITEMSETS (SUPPORT >=30%)

{A,B,C,D,E,F,G}

STEP 3: Generate Candidate 2-items from frequent 
All Combinations of frequent items :

{A,B},{A,C},{A,D},{A,E},{A,F},{A,G}
{B,C},{B,D},{B,E},{B,F},{B,G}
{C,D},{C,E},{C,F},{C,G}
{D,E},{D,F},{D,G}
{E,F},{E,G}
{F,G}

STEP 4: Count each Pair of item's appearance across all transaction 

Items     Frequency    SUPPORT
{A,B}      2           (2/5)*100 : 40%
{A,C}      2           (2/5)*100 : 40%
{A,D}      1           (1/5)*100 : 20%   <- REMOVE
{A,E}      3           (3/5)*100 : 60%
{A,F}      2           (2/5)*100 : 40%

APPLY : FREQUENT ITEMSETS (SUPPORT >=30%)

STEP 5 : CALCULATE CONFIDENCE 

CONFIDENCE {A,B}= 0.40/0.80= 0.5 = 50%

CONFIDENCE {A,C}= 0.40/0.80= 0.5 = 50%

CONFIDENCE {A,E}= 0.60/0.80= 0.5 = 74%

CONFIDENCE {A,F}= 0.40/0.80= 0.5 = 50%

In [3]:
0.60/0.80

0.7499999999999999

In [1]:
data= {
    "C1":["A",'B','C','D','E'],
    "C2":["A",'B','F','G','H'],
    "C3":["N",'Y','C','Z','X'],
    "C4":["F",'C','S','D','E'],
    "C5":["Q",'B','K','V','G'],
    "C6":["A",'F','R','W','E'],
    "C7":["A",'L','C','J','E']
    
}

In [2]:
data

{'C1': ['A', 'B', 'C', 'D', 'E'],
 'C2': ['A', 'B', 'F', 'G', 'H'],
 'C3': ['N', 'Y', 'C', 'Z', 'X'],
 'C4': ['F', 'C', 'S', 'D', 'E'],
 'C5': ['Q', 'B', 'K', 'V', 'G'],
 'C6': ['A', 'F', 'R', 'W', 'E'],
 'C7': ['A', 'L', 'C', 'J', 'E']}

In [3]:
import pandas as pd

In [4]:
D=pd.DataFrame(data)
D

  C1 C2 C3 C4 C5 C6 C7
0  A  A  N  F  Q  A  A
1  B  B  Y  C  B  F  L
2  C  F  C  S  K  R  C
3  D  G  Z  D  V  W  J
4  E  H  X  E  G  E  E

In [6]:
TR=D.values.tolist()
TR

[['A', 'A', 'N', 'F', 'Q', 'A', 'A'],
 ['B', 'B', 'Y', 'C', 'B', 'F', 'L'],
 ['C', 'F', 'C', 'S', 'K', 'R', 'C'],
 ['D', 'G', 'Z', 'D', 'V', 'W', 'J'],
 ['E', 'H', 'X', 'E', 'G', 'E', 'E']]

In [7]:
# step 1: Convert columns to Transactions (rows)
transaction=list(zip(*data.values()))

In [8]:
transaction

[('A', 'A', 'N', 'F', 'Q', 'A', 'A'),
 ('B', 'B', 'Y', 'C', 'B', 'F', 'L'),
 ('C', 'F', 'C', 'S', 'K', 'R', 'C'),
 ('D', 'G', 'Z', 'D', 'V', 'W', 'J'),
 ('E', 'H', 'X', 'E', 'G', 'E', 'E')]

In [ ]:
!pip install mlxtend

In [9]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,association_rules

In [10]:
te=TransactionEncoder()

In [17]:
transaction

[('A', 'A', 'N', 'F', 'Q', 'A', 'A'),
 ('B', 'B', 'Y', 'C', 'B', 'F', 'L'),
 ('C', 'F', 'C', 'S', 'K', 'R', 'C'),
 ('D', 'G', 'Z', 'D', 'V', 'W', 'J'),
 ('E', 'H', 'X', 'E', 'G', 'E', 'E')]

In [13]:
# step 2: Use TransectionEncoder

te_array=te.fit(transaction).transform(transaction)
te_array

array([[ True, False, False, False, False,  True, False, False, False,
        False, False,  True,  True, False, False, False, False, False,
        False, False],
       [False,  True,  True, False, False,  True, False, False, False,
        False,  True, False, False, False, False, False, False, False,
         True, False],
       [False, False,  True, False, False,  True, False, False, False,
         True, False, False, False,  True,  True, False, False, False,
        False, False],
       [False, False, False,  True, False, False,  True, False,  True,
        False, False, False, False, False, False,  True,  True, False,
        False,  True],
       [False, False, False, False,  True, False,  True,  True, False,
        False, False, False, False, False, False, False, False,  True,
        False, False]])

In [21]:
df=pd.DataFrame(te_array,columns=te.columns_)
df

,A,B,C,D,E,F,G,H,J,K,L,N,Q,R,S,V,W,X,Y,Z
0,True,False,False,False,False,True,False,False,False,False,False,True,True,False,False,False,False,False,False,False
1,False,True,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False
2,False,False,True,False,False,True,False,False,False,True,False,False,False,True,True,False,False,False,False,False
3,False,False,False,True,False,False,True,False,True,False,False,False,False,False,False,True,True,False,False,True
4,False,False,False,False,True,False,True,True,False,False,False,False,False,False,False,False,False,True,False,False

In [17]:
# setp 3: Find frequent itemsets
frequent_items=apriori(df,min_support=0.3,use_colnames=True,verbose=1)

Processing 6 combinations | Sampling itemset size 2

In [20]:
frequent_items

In [16]:
# step 4: Generate association Rule

rule=association_rules(frequent_items,metric='confidence',min_threshold=0.6)

In [37]:
rule

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(F),(C),0.6,0.4,0.4,0.666667,1.666667,1.0,0.16,1.8,1.000000,0.666667,0.444444,0.833333
1,(C),(F),0.4,0.6,0.4,1.000000,1.666667,1.0,0.16,inf,0.666667,0.666667,1.000000,0.833333

In [41]:
rule[['antecedents','consequents','support','confidence','lift']]

  antecedents consequents  support  confidence      lift
0         (F)         (C)      0.4    0.666667  1.666667
1         (C)         (F)      0.4    1.000000  1.666667