# Type of Encoding

1. `Maping`
2. `Lable encoding`
3. `Ordinal encoding`
4. `One hand encoding`
5. `Binary encoding`
6. `Frequency encoding`
7. `Hash encoding`
8. `Target encoding`

# 1. Labelencoder

In [2]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [3]:
df=pd.read_csv("employee_detail.csv")

In [4]:
df["Gender"].value_counts()

Gender
Male      200
Female    179
Other     171
Name: count, dtype: int64

# Maping

In [5]:
df['Gender'].map({'Male':0,"Female":1,"Other":2})

0      2
1      0
2      1
3      0
4      1
      ..
545    1
546    0
547    2
548    0
549    0
Name: Gender, Length: 550, dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
for i in df.select_dtypes("object").columns:
    df[i]=label.fit_transform(df[i])

In [7]:
df.head(1)

,Employee_ID,City,Gender,Department,Marital_Status,Education_Level,Satisfaction_Level,Experience_Level,Employee_Rating,Age,Salary,Work_Experience_Years,Hours_Worked_Per_Week,Promotion_Last_Year,Contract_Type,Work_Shift,Remote_Work,Transport,Internet_Availability
0,1001,4,2,5,1,3,1,2,2,46,91696,9,54,1,1,2,0,1,0

# 2. OrdinalEncoder

In [15]:
from sklearn.preprocessing import OrdinalEncoder 
import pandas as pd

In [5]:
df=pd.read_csv("employee_detail.csv")

In [6]:
df['Satisfaction_Level'].value_counts()

Satisfaction_Level
High         120
Very High    117
Low          116
Very Low     105
Medium        92
Name: count, dtype: int64

In [18]:
Satisfaction2=OrdinalEncoder(categories=[["Very Low","Low","Medium","High","Very High"]])

In [1]:
#Satisfaction2.fit_transform(df[["Satisfaction_Level"]])

In [20]:
df.head(1)

,Employee_ID,City,Gender,Department,Marital_Status,Education_Level,Satisfaction_Level,Experience_Level,Employee_Rating,Age,Salary,Work_Experience_Years,Hours_Worked_Per_Week,Promotion_Last_Year,Contract_Type,Work_Shift,Remote_Work,Transport,Internet_Availability
0,1001,Kolkata,Other,Support,Married,PhD,Low,Mid,2,46,91696,9,54,Yes,Full-Time,Night,Allowed,Own Vehicle,Average

In [7]:
df['Experience_Level'].value_counts()

Experience_Level
Lead      144
Junior    143
Senior    139
Mid       124
Name: count, dtype: int64

In [8]:
Satisfaction2=OrdinalEncoder(categories=[["Very Low","Low","Medium","High","Very High"],['Junior','Mid','Senior','Lead']])

In [9]:
Satisfaction2.fit_transform(df[["Satisfaction_Level","Experience_Level"]])

array([[1., 1.],
       [0., 3.],
       [4., 2.],
       ...,
       [2., 3.],
       [3., 1.],
       [0., 3.]])

# 3. One-Hot Encoding

In [2]:
import pandas as pd

In [3]:
data={'color':['red','blue','yellow','white','black']}
df=pd.DataFrame(data)

In [4]:
df

    color
0     red
1    blue
2  yellow
3   white
4   black

In [5]:
pd.get_dummies(df,dtype='int')

   color_black  color_blue  color_red  color_white  color_yellow
0            0           0          1            0             0
1            0           1          0            0             0
2            0           0          0            0             1
3            0           0          0            1             0
4            1           0          0            0             0

In [6]:
pd.get_dummies(df,drop_first=True,dtype='int')

   color_blue  color_red  color_white  color_yellow
0           0          1            0             0
1           1          0            0             0
2           0          0            0             1
3           0          0            1             0
4           0          0            0             0

In [7]:
df=pd.read_csv("employee_detail.csv")

In [8]:
data=df[['City','Marital_Status','Promotion_Last_Year']]

In [9]:
pd.get_dummies(data,columns=['City','Marital_Status','Promotion_Last_Year'],dtype=int,drop_first=True)

,City_Chennai,City_Delhi,City_Hyderabad,City_Kolkata,City_Mumbai,Marital_Status_Married,Marital_Status_Single,Marital_Status_Widow,Promotion_Last_Year_Yes
0,0,0,0,1,0,1,0,0,1
1,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,1,0,0,1
3,0,0,0,0,0,0,1,0,0
4,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...
545,0,0,0,0,1,0,0,1,1
546,0,0,0,0,0,0,0,1,0
547,1,0,0,0,0,1,0,0,1
548,0,0,0,0,1,0,0,0,1
549,1,0,0,0,0,1,0,0,1

In [10]:
from sklearn.preprocessing import OneHotEncoder
encoder1=OneHotEncoder(dtype='int',drop=True)

In [11]:
df=pd.read_csv("employee_detail.csv")

In [30]:
encoder1=OneHotEncoder(dtype=int,drop="first",sparse_output=False)

In [33]:
data=df[['City','Marital_Status','Promotion_Last_Year']]
df1=encoder1.fit_transform(data)

In [34]:
df1

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 1]])

In [35]:
df2=pd.DataFrame(df1,columns=encoder1.get_feature_names_out(data.columns))

In [36]:
df2

,City_Chennai,City_Delhi,City_Hyderabad,City_Kolkata,City_Mumbai,Marital_Status_Married,Marital_Status_Single,Marital_Status_Widow,Promotion_Last_Year_Yes
0,0,0,0,1,0,1,0,0,1
1,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,1,0,0,1
3,0,0,0,0,0,0,1,0,0
4,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...
545,0,0,0,0,1,0,0,1,1
546,0,0,0,0,0,0,0,1,0
547,1,0,0,0,0,1,0,0,1
548,0,0,0,0,1,0,0,0,1
549,1,0,0,0,0,1,0,0,1

# Columns 1
1. A = 30%
2. B = 20%
3. C = 50%
    - ### Label Encoding: {"A":0,"B":1,"C":2}  `# we give them number`
    - ### Maping: `# we give them number`


# Columns 2
1. Good 50%
2. Bad 30%
3. Batter 20%
    - ### Ordinal Encoding: {"Good":1,"Bad":0,"Batter":2} `# we put them in Order`

# Columns 3
1. A
2. G
3. H
4. D
5. X
6. H
    - ### One hot Encoding: `# When we have so many columns`